networks:
  restfull_net:
    driver: bridge
services:
    nginx_restfull:
      container_name: nginx_restfull
      image: nginx:latest
      links:
        - php_restfull
      networks:
        - restfull_net
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
      volumes:
        - ..:/var/www/restfull
        - ${NGINX_CONFIG}:/etc/nginx
      labels:
          org.label-schema.group: "restfull"

    php_restfull:
      build:
        context: .
        dockerfile: ./php/Dockerfile
        args:
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
      container_name: php_restfull
      expose:
        - '9000'
      networks:
        - restfull_net
      volumes:
        - ..:/var/www/restfull
        - ./php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./php/php-ini-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
      labels:
          org.label-schema.group: "restfull"

version: '2'
volumes: {}